import type {
  CirculationMember,
  CirculationBook,
  Loan,
  Fine,
  TransactionLog,
} from "@/types/circulation";

// ─── Members ───────────────────────────────────────────────

export const mockMembers: CirculationMember[] = [
  {
    id: "m1",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "(555) 234-5678",
    memberNumber: "M001234",
    status: "active",
    activeLoans: 2,
    maxLoans: 5,
    totalFinesOwed: 0,
  },
  {
    id: "m2",
    name: "Michael Chen",
    email: "michael.c@email.com",
    phone: "(555) 345-6789",
    memberNumber: "M001235",
    status: "active",
    activeLoans: 3,
    maxLoans: 5,
    totalFinesOwed: 3.75,
  },
  {
    id: "m3",
    name: "Emily Davis",
    email: "emily.d@email.com",
    phone: "(555) 456-7890",
    memberNumber: "M001236",
    status: "suspended",
    activeLoans: 1,
    maxLoans: 5,
    totalFinesOwed: 12.5,
  },
  {
    id: "m4",
    name: "James Wilson",
    email: "james.w@email.com",
    phone: "(555) 567-8901",
    memberNumber: "M001237",
    status: "active",
    activeLoans: 0,
    maxLoans: 5,
    totalFinesOwed: 0,
  },
  {
    id: "m5",
    name: "Olivia Martinez",
    email: "olivia.m@email.com",
    phone: "(555) 678-9012",
    memberNumber: "M001238",
    status: "active",
    activeLoans: 5,
    maxLoans: 5,
    totalFinesOwed: 1.25,
  },
  {
    id: "m6",
    name: "Robert Thompson",
    email: "robert.t@email.com",
    phone: "(555) 789-0123",
    memberNumber: "M001239",
    status: "expired",
    activeLoans: 0,
    maxLoans: 5,
    totalFinesOwed: 25.0,
  },
];

// ─── Books ─────────────────────────────────────────────────

export const mockBooks: CirculationBook[] = [
  {
    id: "b1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0-7432-7356-5",
    available: true,
    copies: 3,
    availableCopies: 1,
  },
  {
    id: "b2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0-06-112008-4",
    available: false,
    copies: 2,
    availableCopies: 0,
  },
  {
    id: "b3",
    title: "1984",
    author: "George Orwell",
    isbn: "978-0-452-28423-4",
    available: true,
    copies: 4,
    availableCopies: 2,
  },
  {
    id: "b4",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0-14-143951-8",
    available: true,
    copies: 2,
    availableCopies: 1,
  },
  {
    id: "b5",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231609-7",
    available: false,
    copies: 3,
    availableCopies: 0,
  },
  {
    id: "b6",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "978-0-316-76948-0",
    available: true,
    copies: 2,
    availableCopies: 2,
  },
  {
    id: "b7",
    title: "Brave New World",
    author: "Aldous Huxley",
    isbn: "978-0-06-085052-4",
    available: true,
    copies: 3,
    availableCopies: 1,
  },
  {
    id: "b8",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0-547-92822-7",
    available: true,
    copies: 5,
    availableCopies: 3,
  },
];

// ─── Loans ─────────────────────────────────────────────────

export const mockLoans: Loan[] = [
  // Active loans
  {
    id: "l1",
    bookId: "b1",
    bookTitle: "The Great Gatsby",
    bookISBN: "978-0-7432-7356-5",
    bookAuthor: "F. Scott Fitzgerald",
    memberId: "m1",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    checkoutDate: "2026-03-03",
    dueDate: "2026-03-17",
    returnDate: null,
    status: "CHECKED_OUT",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l2",
    bookId: "b3",
    bookTitle: "1984",
    bookISBN: "978-0-452-28423-4",
    bookAuthor: "George Orwell",
    memberId: "m1",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    checkoutDate: "2026-03-05",
    dueDate: "2026-03-19",
    returnDate: null,
    status: "CHECKED_OUT",
    renewalCount: 1,
    maxRenewals: 2,
    fine: 0,
    notes: "Renewed once on 2026-03-05",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l3",
    bookId: "b5",
    bookTitle: "Sapiens",
    bookISBN: "978-0-06-231609-7",
    bookAuthor: "Yuval Noah Harari",
    memberId: "m2",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    checkoutDate: "2026-02-28",
    dueDate: "2026-03-14",
    returnDate: null,
    status: "CHECKED_OUT",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Jane Librarian",
  },
  {
    id: "l4",
    bookId: "b7",
    bookTitle: "Brave New World",
    bookISBN: "978-0-06-085052-4",
    bookAuthor: "Aldous Huxley",
    memberId: "m2",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    checkoutDate: "2026-03-01",
    dueDate: "2026-03-15",
    returnDate: null,
    status: "CHECKED_OUT",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l5",
    bookId: "b8",
    bookTitle: "The Hobbit",
    bookISBN: "978-0-547-92822-7",
    bookAuthor: "J.R.R. Tolkien",
    memberId: "m2",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    checkoutDate: "2026-03-08",
    dueDate: "2026-03-22",
    returnDate: null,
    status: "CHECKED_OUT",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l6",
    bookId: "b2",
    bookTitle: "To Kill a Mockingbird",
    bookISBN: "978-0-06-112008-4",
    bookAuthor: "Harper Lee",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    checkoutDate: "2026-03-06",
    dueDate: "2026-03-20",
    returnDate: null,
    status: "CHECKED_OUT",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Jane Librarian",
  },
  // Overdue loans
  {
    id: "l7",
    bookId: "b4",
    bookTitle: "Pride and Prejudice",
    bookISBN: "978-0-14-143951-8",
    bookAuthor: "Jane Austen",
    memberId: "m3",
    memberName: "Emily Davis",
    memberNumber: "M001236",
    checkoutDate: "2026-02-10",
    dueDate: "2026-02-24",
    returnDate: null,
    status: "OVERDUE",
    renewalCount: 2,
    maxRenewals: 2,
    fine: 3.5,
    notes: "Member notified on 2026-02-25",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l8",
    bookId: "b5",
    bookTitle: "Sapiens",
    bookISBN: "978-0-06-231609-7",
    bookAuthor: "Yuval Noah Harari",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    checkoutDate: "2026-02-15",
    dueDate: "2026-03-01",
    returnDate: null,
    status: "OVERDUE",
    renewalCount: 1,
    maxRenewals: 2,
    fine: 2.25,
    notes: "",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l9",
    bookId: "b6",
    bookTitle: "The Catcher in the Rye",
    bookISBN: "978-0-316-76948-0",
    bookAuthor: "J.D. Salinger",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    checkoutDate: "2026-02-08",
    dueDate: "2026-02-22",
    returnDate: null,
    status: "OVERDUE",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 4.0,
    notes: "Second notice sent",
    checkedOutBy: "Jane Librarian",
  },
  {
    id: "l10",
    bookId: "b1",
    bookTitle: "The Great Gatsby",
    bookISBN: "978-0-7432-7356-5",
    bookAuthor: "F. Scott Fitzgerald",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    checkoutDate: "2026-02-12",
    dueDate: "2026-02-26",
    returnDate: null,
    status: "OVERDUE",
    renewalCount: 1,
    maxRenewals: 2,
    fine: 3.0,
    notes: "",
    checkedOutBy: "Staff Admin",
  },
  // Returned loans
  {
    id: "l11",
    bookId: "b3",
    bookTitle: "1984",
    bookISBN: "978-0-452-28423-4",
    bookAuthor: "George Orwell",
    memberId: "m4",
    memberName: "James Wilson",
    memberNumber: "M001237",
    checkoutDate: "2026-02-01",
    dueDate: "2026-02-15",
    returnDate: "2026-02-14",
    status: "RETURNED",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l12",
    bookId: "b4",
    bookTitle: "Pride and Prejudice",
    bookISBN: "978-0-14-143951-8",
    bookAuthor: "Jane Austen",
    memberId: "m1",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    checkoutDate: "2026-01-20",
    dueDate: "2026-02-03",
    returnDate: "2026-02-01",
    status: "RETURNED",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 0,
    notes: "",
    checkedOutBy: "Jane Librarian",
  },
  {
    id: "l13",
    bookId: "b8",
    bookTitle: "The Hobbit",
    bookISBN: "978-0-547-92822-7",
    bookAuthor: "J.R.R. Tolkien",
    memberId: "m4",
    memberName: "James Wilson",
    memberNumber: "M001237",
    checkoutDate: "2026-02-10",
    dueDate: "2026-02-24",
    returnDate: "2026-02-28",
    status: "RETURNED",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 1.0,
    notes: "Returned 4 days late",
    checkedOutBy: "Staff Admin",
  },
  {
    id: "l14",
    bookId: "b6",
    bookTitle: "The Catcher in the Rye",
    bookISBN: "978-0-316-76948-0",
    bookAuthor: "J.D. Salinger",
    memberId: "m2",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    checkoutDate: "2026-01-15",
    dueDate: "2026-01-29",
    returnDate: "2026-01-28",
    status: "RETURNED",
    renewalCount: 1,
    maxRenewals: 2,
    fine: 0,
    notes: "Renewed once",
    checkedOutBy: "Staff Admin",
  },
  // Lost loan
  {
    id: "l15",
    bookId: "b7",
    bookTitle: "Brave New World",
    bookISBN: "978-0-06-085052-4",
    bookAuthor: "Aldous Huxley",
    memberId: "m6",
    memberName: "Robert Thompson",
    memberNumber: "M001239",
    checkoutDate: "2025-12-01",
    dueDate: "2025-12-15",
    returnDate: null,
    status: "LOST",
    renewalCount: 0,
    maxRenewals: 2,
    fine: 25.0,
    notes: "Reported lost by member on 2026-01-10",
    checkedOutBy: "Staff Admin",
  },
];

// ─── Fines ─────────────────────────────────────────────────

export const mockFines: Fine[] = [
  {
    id: "f1",
    loanId: "l7",
    memberId: "m3",
    memberName: "Emily Davis",
    memberNumber: "M001236",
    bookTitle: "Pride and Prejudice",
    amount: 3.5,
    status: "UNPAID",
    reason: "Overdue",
    createdDate: "2026-02-25",
    paidDate: null,
    waivedBy: null,
  },
  {
    id: "f2",
    loanId: "l8",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    bookTitle: "Sapiens",
    amount: 2.25,
    status: "UNPAID",
    reason: "Overdue",
    createdDate: "2026-03-02",
    paidDate: null,
    waivedBy: null,
  },
  {
    id: "f3",
    loanId: "l9",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    bookTitle: "The Catcher in the Rye",
    amount: 4.0,
    status: "UNPAID",
    reason: "Overdue",
    createdDate: "2026-02-23",
    paidDate: null,
    waivedBy: null,
  },
  {
    id: "f4",
    loanId: "l10",
    memberId: "m5",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    bookTitle: "The Great Gatsby",
    amount: 3.0,
    status: "UNPAID",
    reason: "Overdue",
    createdDate: "2026-02-27",
    paidDate: null,
    waivedBy: null,
  },
  {
    id: "f5",
    loanId: "l15",
    memberId: "m6",
    memberName: "Robert Thompson",
    memberNumber: "M001239",
    bookTitle: "Brave New World",
    amount: 25.0,
    status: "UNPAID",
    reason: "Lost",
    createdDate: "2026-01-10",
    paidDate: null,
    waivedBy: null,
  },
  {
    id: "f6",
    loanId: "l13",
    memberId: "m4",
    memberName: "James Wilson",
    memberNumber: "M001237",
    bookTitle: "The Hobbit",
    amount: 1.0,
    status: "PAID",
    reason: "Overdue",
    createdDate: "2026-02-28",
    paidDate: "2026-02-28",
    waivedBy: null,
  },
  {
    id: "f7",
    loanId: "l14",
    memberId: "m2",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    bookTitle: "The Catcher in the Rye",
    amount: 0.75,
    status: "WAIVED",
    reason: "Overdue",
    createdDate: "2026-01-30",
    paidDate: null,
    waivedBy: "Staff Admin",
  },
  {
    id: "f8",
    loanId: "l3",
    memberId: "m2",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    bookTitle: "Sapiens",
    amount: 3.0,
    status: "PAID",
    reason: "Overdue",
    createdDate: "2026-02-20",
    paidDate: "2026-02-22",
    waivedBy: null,
  },
  {
    id: "f9",
    loanId: "l12",
    memberId: "m1",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    bookTitle: "Pride and Prejudice",
    amount: 1.5,
    status: "WAIVED",
    reason: "Overdue",
    createdDate: "2026-02-04",
    paidDate: null,
    waivedBy: "Staff Admin",
  },
  {
    id: "f10",
    loanId: "l11",
    memberId: "m4",
    memberName: "James Wilson",
    memberNumber: "M001237",
    bookTitle: "1984",
    amount: 2.0,
    status: "PAID",
    reason: "Overdue",
    createdDate: "2026-02-16",
    paidDate: "2026-02-18",
    waivedBy: null,
  },
];

// ─── Transaction Log ───────────────────────────────────────

export const mockTransactionLog: TransactionLog[] = [
  {
    id: "t1",
    type: "CHECKOUT",
    loanId: "l1",
    bookTitle: "The Great Gatsby",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    timestamp: "2026-03-03T10:15:00",
    processedBy: "Staff Admin",
    details: "Checked out for 14 days, due 2026-03-17",
  },
  {
    id: "t2",
    type: "CHECKOUT",
    loanId: "l5",
    bookTitle: "The Hobbit",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    timestamp: "2026-03-08T14:30:00",
    processedBy: "Staff Admin",
    details: "Checked out for 14 days, due 2026-03-22",
  },
  {
    id: "t3",
    type: "CHECKOUT",
    loanId: "l6",
    bookTitle: "To Kill a Mockingbird",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    timestamp: "2026-03-06T09:45:00",
    processedBy: "Jane Librarian",
    details: "Checked out for 14 days, due 2026-03-20",
  },
  {
    id: "t4",
    type: "CHECKIN",
    loanId: "l11",
    bookTitle: "1984",
    memberName: "James Wilson",
    memberNumber: "M001237",
    timestamp: "2026-02-14T16:20:00",
    processedBy: "Staff Admin",
    details: "Returned on time, no fines",
  },
  {
    id: "t5",
    type: "CHECKIN",
    loanId: "l12",
    bookTitle: "Pride and Prejudice",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    timestamp: "2026-02-01T11:00:00",
    processedBy: "Jane Librarian",
    details: "Returned 2 days early",
  },
  {
    id: "t6",
    type: "CHECKIN",
    loanId: "l13",
    bookTitle: "The Hobbit",
    memberName: "James Wilson",
    memberNumber: "M001237",
    timestamp: "2026-02-28T10:30:00",
    processedBy: "Staff Admin",
    details: "Returned 4 days late, fine of $1.00 applied",
  },
  {
    id: "t7",
    type: "RENEWAL",
    loanId: "l2",
    bookTitle: "1984",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    timestamp: "2026-03-05T13:15:00",
    processedBy: "Staff Admin",
    details: "Renewed for 14 days, new due date 2026-03-19 (renewal 1 of 2)",
  },
  {
    id: "t8",
    type: "RENEWAL",
    loanId: "l8",
    bookTitle: "Sapiens",
    memberName: "Olivia Martinez",
    memberNumber: "M001238",
    timestamp: "2026-02-28T15:00:00",
    processedBy: "Staff Admin",
    details: "Renewed for 14 days (renewal 1 of 2)",
  },
  {
    id: "t9",
    type: "FINE_PAID",
    loanId: "l13",
    bookTitle: "The Hobbit",
    memberName: "James Wilson",
    memberNumber: "M001237",
    timestamp: "2026-02-28T10:35:00",
    processedBy: "Staff Admin",
    details: "Fine of $1.00 paid at return",
  },
  {
    id: "t10",
    type: "FINE_PAID",
    loanId: "l3",
    bookTitle: "Sapiens",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    timestamp: "2026-02-22T09:00:00",
    processedBy: "Jane Librarian",
    details: "Overdue fine of $3.00 paid",
  },
  {
    id: "t11",
    type: "FINE_WAIVED",
    loanId: "l14",
    bookTitle: "The Catcher in the Rye",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    timestamp: "2026-01-30T14:00:00",
    processedBy: "Staff Admin",
    details: "Fine of $0.75 waived — first-time forgiveness",
  },
  {
    id: "t12",
    type: "FINE_WAIVED",
    loanId: "l12",
    bookTitle: "Pride and Prejudice",
    memberName: "Sarah Johnson",
    memberNumber: "M001234",
    timestamp: "2026-02-04T11:30:00",
    processedBy: "Staff Admin",
    details: "Fine of $1.50 waived — system error",
  },
  {
    id: "t13",
    type: "CHECKOUT",
    loanId: "l3",
    bookTitle: "Sapiens",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    timestamp: "2026-02-28T09:00:00",
    processedBy: "Jane Librarian",
    details: "Checked out for 14 days, due 2026-03-14",
  },
  {
    id: "t14",
    type: "CHECKOUT",
    loanId: "l4",
    bookTitle: "Brave New World",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    timestamp: "2026-03-01T10:00:00",
    processedBy: "Staff Admin",
    details: "Checked out for 14 days, due 2026-03-15",
  },
  {
    id: "t15",
    type: "FINE_PAID",
    loanId: "l11",
    bookTitle: "1984",
    memberName: "James Wilson",
    memberNumber: "M001237",
    timestamp: "2026-02-18T14:15:00",
    processedBy: "Staff Admin",
    details: "Fine of $2.00 paid",
  },
  {
    id: "t16",
    type: "CHECKIN",
    loanId: "l14",
    bookTitle: "The Catcher in the Rye",
    memberName: "Michael Chen",
    memberNumber: "M001235",
    timestamp: "2026-01-28T16:00:00",
    processedBy: "Staff Admin",
    details: "Returned on time after renewal",
  },
];
