import { Book } from "@/types/book";

export const MOCK_BOOKS: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0-7432-7356-5",
    dewey: "813.52",
    category: "Literature",
    location: "Section A-2, Shelf 3",
    status: "available",
    copies: 3,
    publisher: "Scribner",
    publishYear: 1925,
    edition: "Reprint",
    language: "English",
    pageCount: 180,
    description:
      "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, set in the Jazz Age on Long Island.",
    subjects: ["American Fiction", "Jazz Age", "Classic Literature"],
    coverImageUrl: "",
    dateAdded: "2024-01-15",
    lastModified: "2024-06-10",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0-06-112008-4",
    dewey: "813.54",
    category: "Literature",
    location: "Section B-1, Shelf 2",
    status: "checked-out",
    copies: 2,
    publisher: "J. B. Lippincott & Co.",
    publishYear: 1960,
    edition: "50th Anniversary",
    language: "English",
    pageCount: 281,
    description:
      "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
    subjects: ["American Fiction", "Race Relations", "Southern Gothic"],
    coverImageUrl: "",
    dateAdded: "2024-01-15",
    lastModified: "2024-09-22",
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    isbn: "978-0-452-28423-4",
    dewey: "823.912",
    category: "Literature",
    location: "Section B-1, Shelf 5",
    status: "available",
    copies: 4,
    publisher: "Signet Classic",
    publishYear: 1949,
    edition: "Centennial",
    language: "English",
    pageCount: 328,
    description:
      "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
    subjects: ["Dystopian Fiction", "Political Fiction", "British Literature"],
    coverImageUrl: "",
    dateAdded: "2024-02-01",
    lastModified: "2024-02-01",
  },
  {
    id: "4",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231609-7",
    dewey: "909",
    category: "History & Geography",
    location: "Section C-1, Shelf 4",
    status: "available",
    copies: 2,
    publisher: "Harper",
    publishYear: 2015,
    edition: "1st",
    language: "English",
    pageCount: 464,
    description:
      "A brief history of humankind from the Stone Age to the twenty-first century.",
    subjects: ["World History", "Anthropology", "Civilization"],
    coverImageUrl: "",
    dateAdded: "2024-02-10",
    lastModified: "2024-02-10",
  },
  {
    id: "5",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0-553-38016-3",
    dewey: "530.1",
    category: "Science",
    location: "Section C-1, Shelf 8",
    status: "maintenance",
    copies: 1,
    publisher: "Bantam Books",
    publishYear: 1988,
    edition: "Updated & Expanded",
    language: "English",
    pageCount: 212,
    description:
      "A landmark volume in science writing exploring the origin and fate of the universe.",
    subjects: ["Cosmology", "Physics", "Popular Science"],
    coverImageUrl: "",
    dateAdded: "2024-02-15",
    lastModified: "2025-01-05",
  },
  {
    id: "6",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0-14-143951-8",
    dewey: "823.7",
    category: "Literature",
    location: "Section A-1, Shelf 1",
    status: "available",
    copies: 5,
    publisher: "Penguin Classics",
    publishYear: 1813,
    edition: "Revised",
    language: "English",
    pageCount: 432,
    description:
      "The story follows the main character Elizabeth Bennet as she deals with issues of manners, upbringing, morality, and marriage.",
    subjects: ["British Literature", "Romance", "Classic Literature"],
    coverImageUrl: "",
    dateAdded: "2024-01-15",
    lastModified: "2024-01-15",
  },
  {
    id: "7",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0-547-92822-7",
    dewey: "823.912",
    category: "Literature",
    location: "Section B-2, Shelf 6",
    status: "checked-out",
    copies: 3,
    publisher: "Houghton Mifflin Harcourt",
    publishYear: 1937,
    edition: "75th Anniversary",
    language: "English",
    pageCount: 310,
    description:
      "Bilbo Baggins is a hobbit who enjoys a comfortable life, until he is swept away on an unexpected journey by a wizard and thirteen dwarves.",
    subjects: ["Fantasy", "Adventure", "British Literature"],
    coverImageUrl: "",
    dateAdded: "2024-03-01",
    lastModified: "2024-11-15",
  },
  {
    id: "8",
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    isbn: "978-0-19-929114-4",
    dewey: "576.8",
    category: "Science",
    location: "Section C-2, Shelf 3",
    status: "available",
    copies: 2,
    publisher: "Oxford University Press",
    publishYear: 1976,
    edition: "40th Anniversary",
    language: "English",
    pageCount: 544,
    description:
      "Richard Dawkins' brilliant reformulation of the theory of natural selection, focusing on the gene as the unit of evolution.",
    subjects: ["Evolutionary Biology", "Genetics", "Popular Science"],
    coverImageUrl: "",
    dateAdded: "2024-03-10",
    lastModified: "2024-03-10",
  },
  {
    id: "9",
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    isbn: "978-0-06-093434-7",
    dewey: "863.3",
    category: "Literature",
    location: "Section A-3, Shelf 2",
    status: "available",
    copies: 2,
    publisher: "Ecco",
    publishYear: 1605,
    edition: "Translated by Edith Grossman",
    language: "Spanish",
    pageCount: 940,
    description:
      "The story of a man who becomes so enchanted by reading romances of chivalry that he sets out to revive knighthood.",
    subjects: ["Spanish Literature", "Classic Literature", "Satire"],
    coverImageUrl: "",
    dateAdded: "2024-04-01",
    lastModified: "2024-04-01",
  },
  {
    id: "10",
    title: "The Art of War",
    author: "Sun Tzu",
    isbn: "978-1-59030-227-8",
    dewey: "355.02",
    category: "Social Sciences",
    location: "Section D-1, Shelf 1",
    status: "available",
    copies: 4,
    publisher: "Shambhala",
    publishYear: -500,
    edition: "Illustrated",
    language: "Chinese",
    pageCount: 273,
    description:
      "An ancient Chinese military treatise dating from the Late Spring and Autumn Period, widely regarded as a masterpiece of strategy.",
    subjects: ["Military Strategy", "Philosophy", "Chinese Classics"],
    coverImageUrl: "",
    dateAdded: "2024-04-15",
    lastModified: "2024-04-15",
  },
  {
    id: "11",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    isbn: "978-0-262-04630-5",
    dewey: "005.1",
    category: "Computer Science, Information & General Works",
    location: "Section E-1, Shelf 1",
    status: "available",
    copies: 3,
    publisher: "MIT Press",
    publishYear: 2022,
    edition: "4th",
    language: "English",
    pageCount: 1312,
    description:
      "A comprehensive textbook on computer algorithms, widely used as the textbook for algorithms courses at universities worldwide.",
    subjects: ["Computer Science", "Algorithms", "Data Structures"],
    coverImageUrl: "",
    dateAdded: "2024-05-01",
    lastModified: "2024-05-01",
  },
  {
    id: "12",
    title: "Le Petit Prince",
    author: "Antoine de Saint-Exupéry",
    isbn: "978-0-15-601219-5",
    dewey: "843.912",
    category: "Literature",
    location: "Section A-3, Shelf 4",
    status: "checked-out",
    copies: 2,
    publisher: "Mariner Books",
    publishYear: 1943,
    edition: "Bilingual",
    language: "French",
    pageCount: 96,
    description:
      "A poetic tale in which a pilot stranded in the desert meets a young prince visiting Earth from a tiny asteroid.",
    subjects: ["French Literature", "Children's Literature", "Philosophy"],
    coverImageUrl: "",
    dateAdded: "2024-05-10",
    lastModified: "2024-12-01",
  },
  {
    id: "13",
    title: "The Origin of Species",
    author: "Charles Darwin",
    isbn: "978-0-451-52906-0",
    dewey: "576.82",
    category: "Science",
    location: "Section C-2, Shelf 5",
    status: "available",
    copies: 2,
    publisher: "Signet",
    publishYear: 1859,
    edition: "150th Anniversary",
    language: "English",
    pageCount: 576,
    description:
      "Darwin's foundational work introducing the scientific theory of evolution by means of natural selection.",
    subjects: ["Evolution", "Natural History", "Biology"],
    coverImageUrl: "",
    dateAdded: "2024-05-20",
    lastModified: "2024-05-20",
  },
  {
    id: "14",
    title: "Critique of Pure Reason",
    author: "Immanuel Kant",
    isbn: "978-0-14-044747-7",
    dewey: "121",
    category: "Philosophy & Psychology",
    location: "Section D-2, Shelf 3",
    status: "available",
    copies: 1,
    publisher: "Penguin Classics",
    publishYear: 1781,
    edition: "Revised",
    language: "German",
    pageCount: 784,
    description:
      "One of the most influential works in the history of philosophy, examining the limits and possibilities of human knowledge.",
    subjects: ["Philosophy", "Epistemology", "Metaphysics"],
    coverImageUrl: "",
    dateAdded: "2024-06-01",
    lastModified: "2024-06-01",
  },
  {
    id: "15",
    title: "The Code Book",
    author: "Simon Singh",
    isbn: "978-0-385-49532-5",
    dewey: "652.8",
    category: "Technology",
    location: "Section E-2, Shelf 2",
    status: "checked-out",
    copies: 2,
    publisher: "Anchor",
    publishYear: 2000,
    edition: "1st",
    language: "English",
    pageCount: 432,
    description:
      "A history of secret communication from ancient Egypt to quantum cryptography.",
    subjects: ["Cryptography", "History of Science", "Mathematics"],
    coverImageUrl: "",
    dateAdded: "2024-06-15",
    lastModified: "2025-02-10",
  },
  {
    id: "16",
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "978-0-14-044933-4",
    dewey: "188",
    category: "Philosophy & Psychology",
    location: "Section D-2, Shelf 1",
    status: "available",
    copies: 3,
    publisher: "Penguin Classics",
    publishYear: 180,
    edition: "Translated by Martin Hammond",
    language: "English",
    pageCount: 254,
    description:
      "A series of personal writings by the Roman Emperor, recording his private notes to himself on Stoic philosophy.",
    subjects: ["Stoicism", "Philosophy", "Self-Improvement"],
    coverImageUrl: "",
    dateAdded: "2024-07-01",
    lastModified: "2024-07-01",
  },
  {
    id: "17",
    title: "The Joy of Cooking",
    author: "Irma S. Rombauer",
    isbn: "978-1-5011-6971-7",
    dewey: "641.5",
    category: "Technology",
    location: "Section F-1, Shelf 2",
    status: "available",
    copies: 2,
    publisher: "Scribner",
    publishYear: 2019,
    edition: "2019 Edition",
    language: "English",
    pageCount: 1200,
    description:
      "The bestselling cookbook of all time, updated for modern cooks with over 4,000 recipes.",
    subjects: ["Cooking", "Recipes", "Reference"],
    coverImageUrl: "",
    dateAdded: "2024-07-15",
    lastModified: "2024-07-15",
  },
  {
    id: "18",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    isbn: "978-0-06-088328-7",
    dewey: "863.64",
    category: "Literature",
    location: "Section A-3, Shelf 6",
    status: "available",
    copies: 3,
    publisher: "Harper Perennial",
    publishYear: 1967,
    edition: "Translated by Gregory Rabassa",
    language: "Spanish",
    pageCount: 417,
    description:
      "The multi-generational story of the Buendía family in the mythical town of Macondo.",
    subjects: [
      "Magical Realism",
      "Latin American Literature",
      "Family Saga",
    ],
    coverImageUrl: "",
    dateAdded: "2024-08-01",
    lastModified: "2024-08-01",
  },
  {
    id: "19",
    title: "The Elements of Style",
    author: "William Strunk Jr.",
    isbn: "978-0-205-30902-3",
    dewey: "428.2",
    category: "Language",
    location: "Section D-3, Shelf 1",
    status: "maintenance",
    copies: 4,
    publisher: "Pearson",
    publishYear: 2000,
    edition: "4th",
    language: "English",
    pageCount: 105,
    description:
      "A prescriptive American English writing style guide comprising eight elementary rules of usage and ten principles of composition.",
    subjects: ["Writing", "English Language", "Style Guide"],
    coverImageUrl: "",
    dateAdded: "2024-08-15",
    lastModified: "2025-03-01",
  },
  {
    id: "20",
    title: "Genji Monogatari",
    author: "Murasaki Shikibu",
    isbn: "978-0-14-243714-8",
    dewey: "895.63",
    category: "Literature",
    location: "Section A-4, Shelf 2",
    status: "available",
    copies: 1,
    publisher: "Penguin Classics",
    publishYear: 1008,
    edition: "Translated by Royall Tyler",
    language: "Japanese",
    pageCount: 1216,
    description:
      "Often called the world's first novel, this masterpiece of Japanese literature tells the story of the son of an ancient Japanese emperor.",
    subjects: [
      "Japanese Literature",
      "Classic Literature",
      "Court Life",
    ],
    coverImageUrl: "",
    dateAdded: "2024-09-01",
    lastModified: "2024-09-01",
  },
];
