import type {
  ShelfFlowNode,
  ShelfTemplate,
  ColorPreset,
} from "./types";

export const COLOR_PRESETS: ColorPreset[] = [
  { name: "Navy", value: "#1B2A4A" },
  { name: "Copper", value: "#C4956A" },
  { name: "Sage", value: "#3D8B7A" },
  { name: "Amber", value: "#D4A026" },
  { name: "Slate", value: "#64748B" },
  { name: "Brick", value: "#C4454D" },
  { name: "Plum", value: "#8B6BB5" },
  { name: "Teal", value: "#5EADBD" },
];

export const SHELF_TEMPLATES: ShelfTemplate[] = [
  {
    type: "single-shelf",
    label: "Single Shelf Unit",
    icon: "BookOpen",
    description: "Standard single-sided bookshelf",
    defaultData: {
      shelfType: "single-shelf",
      category: "Fiction",
      deweyRangeStart: "800",
      deweyRangeEnd: "899",
      numberOfTiers: 4,
      capacityPerTier: 30,
      currentUsed: 0,
      notes: "",
      color: "#1B2A4A",
      rotation: 0,
      width: 260,
      height: 90,
    },
  },
  {
    type: "double-shelf",
    label: "Double Shelf Unit",
    icon: "LayoutGrid",
    description: "Double-sided bookshelf with back-to-back access",
    defaultData: {
      shelfType: "double-shelf",
      category: "Non-Fiction",
      deweyRangeStart: "500",
      deweyRangeEnd: "599",
      numberOfTiers: 6,
      capacityPerTier: 40,
      currentUsed: 0,
      notes: "",
      color: "#3D8B7A",
      rotation: 0,
      width: 300,
      height: 100,
    },
  },
  {
    type: "end-cap",
    label: "End Cap",
    icon: "Square",
    description: "Small display at the end of a shelf row",
    defaultData: {
      shelfType: "end-cap",
      category: "Uncategorized",
      deweyRangeStart: "",
      deweyRangeEnd: "",
      numberOfTiers: 3,
      capacityPerTier: 10,
      currentUsed: 0,
      notes: "",
      color: "#8B6BB5",
      rotation: 90,
      width: 180,
      height: 90,
    },
  },
  {
    type: "display-table",
    label: "Display Table",
    icon: "Table",
    description: "Flat table for featured books and new arrivals",
    defaultData: {
      shelfType: "display-table",
      category: "Uncategorized",
      deweyRangeStart: "",
      deweyRangeEnd: "",
      numberOfTiers: 1,
      capacityPerTier: 20,
      currentUsed: 0,
      notes: "",
      color: "#D4A026",
      rotation: 0,
      width: 260,
      height: 80,
    },
  },
  {
    type: "reading-nook",
    label: "Reading Nook",
    icon: "Armchair",
    description: "Cozy seating area with a small shelf nearby",
    defaultData: {
      shelfType: "reading-nook",
      category: "Uncategorized",
      deweyRangeStart: "",
      deweyRangeEnd: "",
      numberOfTiers: 2,
      capacityPerTier: 8,
      currentUsed: 0,
      notes: "",
      color: "#C4956A",
      rotation: 0,
      width: 240,
      height: 90,
    },
  },
];

export const INITIAL_NODES: ShelfFlowNode[] = [
  {
    id: "shelf-1",
    type: "shelf",
    position: { x: 60, y: 60 },
    style: { width: 260, height: 90 },
    data: {
      label: "Fiction A–D",
      shelfType: "single-shelf",
      category: "Fiction",
      deweyRangeStart: "813",
      deweyRangeEnd: "823",
      numberOfTiers: 4,
      capacityPerTier: 38,
      currentUsed: 142,
      sectionCode: "A-1",
      notes: "Main fiction section, high traffic area",
      color: "#1B2A4A",
      rotation: 0,
      width: 260,
      height: 90,
    },
  },
  {
    id: "shelf-2",
    type: "shelf",
    position: { x: 380, y: 60 },
    style: { width: 260, height: 90 },
    data: {
      label: "Fiction E–K",
      shelfType: "single-shelf",
      category: "Fiction",
      deweyRangeStart: "823",
      deweyRangeEnd: "840",
      numberOfTiers: 4,
      capacityPerTier: 38,
      currentUsed: 101,
      sectionCode: "A-2",
      notes: "",
      color: "#1B2A4A",
      rotation: 0,
      width: 260,
      height: 90,
    },
  },
  {
    id: "shelf-3",
    type: "shelf",
    position: { x: 60, y: 200 },
    style: { width: 300, height: 100 },
    data: {
      label: "Science & Technology",
      shelfType: "double-shelf",
      category: "Science",
      deweyRangeStart: "500",
      deweyRangeEnd: "599",
      numberOfTiers: 6,
      capacityPerTier: 40,
      currentUsed: 166,
      sectionCode: "C-1",
      notes: "Non-fiction science section",
      color: "#3D8B7A",
      rotation: 0,
      width: 300,
      height: 100,
    },
  },
  {
    id: "shelf-4",
    type: "shelf",
    position: { x: 420, y: 210 },
    style: { width: 260, height: 80 },
    data: {
      label: "New Arrivals",
      shelfType: "display-table",
      category: "Uncategorized",
      deweyRangeStart: "",
      deweyRangeEnd: "",
      numberOfTiers: 1,
      capacityPerTier: 20,
      currentUsed: 14,
      sectionCode: "D-1",
      notes: "Featured books and recent acquisitions",
      color: "#D4A026",
      rotation: 0,
      width: 260,
      height: 80,
    },
  },
];
