import { ShelfSection } from "@/components/map/types";

export const shelfSections: ShelfSection[] = [
  {
    id: "A1",
    name: "Section A-1",
    category: "Fiction A-D",
    capacity: 150,
    used: 142,
    x: 56,
    y: 120,
    width: 128,
    height: 70,
    books: [
      { title: "Pride and Prejudice", author: "Jane Austen", dewey: "823.7", color: "#4F46E5" },
      { title: "The Catcher in the Rye", author: "J. D. Salinger", dewey: "813.54", color: "#2563EB" },
      { title: "Animal Farm", author: "George Orwell", dewey: "823.912", color: "#1D4ED8" },
      { title: "Jane Eyre", author: "Charlotte Bronte", dewey: "823.8", color: "#4338CA" },
    ],
  },
  {
    id: "A2",
    name: "Section A-2",
    category: "Fiction E-K",
    capacity: 150,
    used: 101,
    x: 206,
    y: 120,
    width: 128,
    height: 70,
    books: [
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald", dewey: "813.52", color: "#9333EA" },
      { title: "Brave New World", author: "Aldous Huxley", dewey: "823.912", color: "#7C3AED" },
      { title: "Fahrenheit 451", author: "Ray Bradbury", dewey: "813.54", color: "#6D28D9" },
    ],
  },
  {
    id: "B1",
    name: "Section B-1",
    category: "Fiction L-R",
    capacity: 150,
    used: 135,
    x: 56,
    y: 232,
    width: 128,
    height: 70,
    books: [
      { title: "To Kill a Mockingbird", author: "Harper Lee", dewey: "813.54", color: "#0EA5E9" },
      { title: "1984", author: "George Orwell", dewey: "823.912", color: "#0284C7" },
      { title: "Moby-Dick", author: "Herman Melville", dewey: "813.3", color: "#0369A1" },
    ],
  },
  {
    id: "B2",
    name: "Section B-2",
    category: "Fiction S-Z",
    capacity: 150,
    used: 141,
    x: 206,
    y: 232,
    width: 128,
    height: 70,
    books: [
      { title: "The Hobbit", author: "J. R. R. Tolkien", dewey: "823.912", color: "#16A34A" },
      { title: "Wuthering Heights", author: "Emily Bronte", dewey: "823.8", color: "#15803D" },
      { title: "The Sun Also Rises", author: "Ernest Hemingway", dewey: "813.52", color: "#166534" },
    ],
  },
  {
    id: "C1",
    name: "Section C-1",
    category: "Non-Fiction 000-500",
    capacity: 200,
    used: 166,
    x: 392,
    y: 120,
    width: 140,
    height: 70,
    books: [
      { title: "A Brief History of Time", author: "Stephen Hawking", dewey: "530.1", color: "#EA580C" },
      { title: "The Selfish Gene", author: "Richard Dawkins", dewey: "576.8", color: "#C2410C" },
      { title: "Clean Code", author: "Robert C. Martin", dewey: "005.1", color: "#9A3412" },
    ],
  },
  {
    id: "C2",
    name: "Section C-2",
    category: "Non-Fiction 500-900",
    capacity: 200,
    used: 179,
    x: 392,
    y: 232,
    width: 140,
    height: 70,
    books: [
      { title: "Sapiens", author: "Yuval Noah Harari", dewey: "909", color: "#DC2626" },
      { title: "Guns, Germs, and Steel", author: "Jared Diamond", dewey: "303.4", color: "#B91C1C" },
      { title: "The Silk Roads", author: "Peter Frankopan", dewey: "950", color: "#991B1B" },
    ],
  },
];
